services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
        #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - "${DOCKER_VOLUME_PATH}"/jellyfin:/config
      - "${MEDIA_MOUNT_PATH}"/movies:/movies
      - "${MEDIA_MOUNT_PATH}"/tv-shows:/tvshows
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - torrent-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.pi.local`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

networks:
  torrent-net:
    external: true
