services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - WEBUI_PORT=8081
    volumes:
      - "$DOCKER_VOLUME_PATH/qbittorrent:/config"
      - "$DOWNLOADS_MOUNT_PATH:/downloads"
      - "$MEDIA_MOUNT_PATH/movies:/movies"
      - "$MEDIA_MOUNT_PATH/tv-shows:/tv-shows"
    network_mode: container:gluetun # run on the vpn network
