services:
  gluetun:
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    container_name: gluetun
    networks:
      - internal-net
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8081:8081"     # qBittorrent
      - "9091:9091"     # transmission
      - "8888:8888/tcp" # HTTP proxy
    volumes:
      - "$DOCKER_VOLUME_PATH/gluetun:/gluetun"
    environment:
      - HTTPPROXY=on
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      # Wireguard:
      - SERVER_HOSTNAMES=uk-lon.prod.surfshark.com
      - WIREGUARD_PRIVATE_KEY=uDymMz0D2jX5ZPTXNHoCRJVcDsXZgMXaNiEGXJ7Eknk=
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      # Enable control server for healthcheck (still useful for other purposes if needed)
      - CONTROL_SERVER_ADDRESS=:8000
      - CONTROL_SERVER_LOG=off
    # Removed custom healthcheck to allow Docker to use the image's default

networks:
  internal-net:
    external: true
