- name: Set default value of is_docker to false
  set_fact:
    is_docker: false

- name: Check if running inside Docker
  stat:
    path: /.dockerenv
  register: docker_check

- name: Set fact is_docker to true if inside Docker
  set_fact:
    is_docker: true
  when: docker_check.stat.exists

- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  become: true
  apt:
    upgrade: dist

- name: Install packages
  become: true
  apt:
    pkg:
      - git
      - curl
      - neovim
      - lsb-release # for docker
      - kmod # for modprobe