- name: Disable swap
  shell: dphys-swapfile swapoff
  become: true
  ignore_errors: "{{ is_docker | bool }}"

- name: Edit swap
  lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE'
    line: "CONF_SWAPSIZE={{ swap_size_mb }}"
  become: true

- name: Setup swap
  shell: dphys-swapfile setup
  become: true

- name: Enable swap
  shell: dphys-swapfile swapon
  become: true
  ignore_errors: "{{ is_docker | bool }}"
