services:
  plex:
    container_name: plex
    restart: unless-stopped
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    devices:
      - /dev/dri/:/dev/dri/
    environment:
      - PLEX_CLAIM=claim-_iTNsgq24TywaTzPFhBp
      - PUID=0
      - PGID=0
      - VERSION=docker
    volumes:
      - "$DOCKER_VOLUME_PATH/plex/config:/config"
      - "$MEDIA_MOUNT_PATH/movies:/movies"
      - "$MEDIA_MOUNT_PATH/movies4k:/movies4k"
      - "$MEDIA_MOUNT_PATH/tv-shows:/tv"
      - "$DOCKER_VOLUME_PATH/plex/transcode:/transcode"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/identity"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m
