services:
  plex:
    container_name: plex
    restart: unless-stopped
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PLEX_CLAIM=claim-_iTNsgq24TywaTzPFhBp
      - PUID=1001
      - PGID=1001
      - VERSION=docker
    volumes:
      - "$DOCKER_VOLUME_PATH/plex/config:/config"
      - "$MEDIA_MOUNT_PATH/movies:/movies"
      - "$MEDIA_MOUNT_PATH/movies4k:/movies4k"
      - "$MEDIA_MOUNT_PATH/tv-shows:/tv"
      - "$DOCKER_VOLUME_PATH/plex/transcode:/transcode"

