export DOCKER_VOLUME_PATH="/storage/docker/home-server"
export MEDIA_MOUNT_PATH="/storage/media"
export DOWNLOADS_MOUNT_PATH="/storage/downloads"
export DOMAIN="mcg.local"
export PRIMARY_IP="192.168.0.100"
