services:
  tailscale-network:
    image: ghcr.io/tailscale/tailscale:latest
    hostname: tailscale-network
    container_name: tailscale-network
    environment:
      - PUID=1001
      - PGID=1001
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:container --advertise-routes=192.168.88.0/24
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - "$DOCKER_VOLUME_PATH/tailscale:/var/lib/tailscale"
      - /lib/modules:/lib/modules
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      #- SYS_MODULE
    privileged: true
    network_mode: "host"
    restart: unless-stopped
