version: "3"

services:
  watchtower:
    image: containrrr/watchtower:armhf-latest
    environment:
      #      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_RUN_ONCE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "$HOME/.docker/config.json:/config.json"
    command: --interval 86400
