services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    container_name: traefik
    environment:
      - PUID=0
      - PGID=0
      - DOMAIN=${DOMAIN}
      - PRIMARY_IP=${PRIMARY_IP}
      - PVE_IP=${PVE_IP}
      - NETWORK_IP=${NETWORK_IP}
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - --serversTransport.insecureSkipVerify=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - ./entrypoint.sh:/entrypoint.sh
      - ./routes.yml:/routes.yml.template
    networks:
      - internal-net


networks:
  internal-net:
    external: true
