version: "3.7"
services:
  tailscale-pi:
    image: ghcr.io/tailscale/tailscale:latest
    hostname: tailscale-pi
    environment:
      - TS_AUTHKEY=${TS_CLIENT_SECRET}?ephemeral=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=false
    volumes:
      - ${MNT_DOCKER_HS}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    privileged: true
    network_mode: "host"
    restart: unless-stopped
