version: "3.7"
services:
  tailscale-pi:
    image: ghcr.io/tailscale/tailscale:latest
    hostname: tailscale-pi
    container_name: tailscale-pi
    environment:
      - TS_AUTHKEY=$TS_AUTH_KEY
        #- TS_EXTRA_ARGS=--reset
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --advertise-routes=192.168.1.0/24,192.168.0.0/24
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - "$DOCKER_VOLUME_PATH/tailscale:/var/lib/tailscale"
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    network_mode: "host"
    restart: unless-stopped
