- name: Find app preference plist files
  ansible.builtin.find:
    paths: "{{ ansible_facts.env.HOME }}/.config/macos-preferences"
    patterns: "*.plist"
  register: plist_files

- name: Import app preferences
  ansible.builtin.command:
    cmd: "defaults import {{ item.path | basename | regex_replace('\\.plist$', '') }} {{ item.path }}"
  loop: "{{ plist_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  changed_when: true

- name: Flush preferences cache
  ansible.builtin.command: killall cfprefsd
  changed_when: true
  ignore_errors: true
