- name: Set key repeat rate
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2

- name: Set initial key repeat delay
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15

- name: Show all file extensions in Finder
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

- name: Show path bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

- name: Set Dock icon size
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 36

- name: Autohide Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: Remove Dock autohide delay
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0

- name: Disable natural scrolling
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false

- name: Enable tap to click on trackpad
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: bool
    value: true

- name: Disable auto-correct
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: Restart Dock to apply changes
  ansible.builtin.command: killall Dock
  changed_when: true

- name: Restart Finder to apply changes
  ansible.builtin.command: killall Finder
  changed_when: true
