services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba-server
    network_mode: host
    volumes:
      - ./myshare:/shares/media
      - ./config:/etc/samba
      - /etc/avahi/services/:/external/avahi
    environment:
      SAMBA_SHARE_NAME: Public
      WSDD2_DISABLE: 1
      SAMBA_SHARE_BROWSABLE: yes
      SAMBA_SHARE_WRITABLE: yes
      SAMBA_SHARE_GUEST_OK: yes
      SAMBA_CONF_LOG_LEVEL: 5
      SAMBA_VOLUME_CONFIG_public: "[Public]; path=/shares/media; guest ok = yes; read only = no; browseable = yes"
    restart: unless-stopped

