services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:arm64v8-latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - /mnt/ssd/docker/home-server/qbittorrent:/config
      - /mnt/ssd/downloads:/downloads
      - /mnt/ssd/media/movies:/movies
      - /mnt/ssd/media/tv-shows:/tv-shows
    restart: unless-stopped
    network_mode: container:gluetun # run on the vpn network
