services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:arm64v8-latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
        #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /mnt/ssd/docker/home-server/jellyfin:/config
      - /mnt/ssd/media/movies:/movies
      - /mnt/ssd/media/tv-shows:/tvshows
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - torrent-net
    restart: unless-stopped

networks:
  torrent-net:
    external: true
