version: '3'
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:arm64v8-latest
    network_mode: host
    environment:
      - PLEX_CLAIM=claim-_iTNsgq24TywaTzPFhBp
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt/ssd/docker/home-server/plex/config:/config
      - /mnt/ssd/media/movies:/movies
      - /mnt/ssd/media/tv-shows:/tv
      - /mnt/ssd/docker/home-server/plex/transcode:/transcode
    restart: unless-stopped

