version: '3'
services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.13
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - "8191:8191" # Optional: only needed if you want to access FlareSolverr outside of the Docker network
    networks:
      - torrent-net

  radarr:
    image: lscr.io/linuxserver/radarr:arm64v8-latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/docker/home-server/radarr:/config
      - /mnt/ssd/media/movies:/movies #optional
      - /mnt/ssd/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - torrent-net


  sonarr:
    image: lscr.io/linuxserver/sonarr:arm64v8-latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/docker/home-server/sonarr:/config
      - /mnt/ssd/media/tv-shows:/tv #optional
      - /mnt/ssd/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - torrent-net

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:arm64v8-latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/ssd/docker/home-server/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - torrent-net

  overseerr:
    image: lscr.io/linuxserver/overseerr:arm64v8-latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/docker/home-server/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      - torrent-net

networks:
  torrent-net:
    external: true

