version: '3'
services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.13
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - "8191:8191" # Optional: only needed if you want to access FlareSolverr outside of the Docker network
    networks:
      - internal-net

  radarr:
    image: lscr.io/linuxserver/radarr:arm64v8-latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/docker/home-server/radarr:/config
      - /mnt/ssd/media/movies:/movies #optional
      - /mnt/ssd/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.pi.local`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - internal-net


  sonarr:
    image: lscr.io/linuxserver/sonarr:arm64v8-latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/docker/home-server/sonarr:/config
      - /mnt/ssd/media/tv-shows:/tv #optional
      - /mnt/ssd/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.pi.local`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - internal-net

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:arm64v8-latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/ssd/docker/home-server/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.pi.local`)"
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    networks:
      - internal-net

  overseerr:
    image: lscr.io/linuxserver/overseerr:arm64v8-latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/docker/home-server/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`requests.pi.local`)"
      - "traefik.http.routers.overseerr.entrypoints=web"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
    networks:
      - internal-net

networks:
  internal-net:
    external: true

