- name: macOS Laptop Setup
  gather_facts: true
  hosts: localhost
  connection: local
  vars:
    git_user_email: mcgroas@tcd.ie
    git_user_name: mcgizzle
    dotfiles_repo: "git@github.com:mcgizzle/dotfiles.git"
    cfg_dir: "{{ ansible_facts.env.HOME }}/.cfg"
  tasks:
    - name: Dotfiles
      ansible.builtin.include_tasks:
        file: tasks/dotfiles.yml

    - name: Homebrew
      ansible.builtin.include_tasks:
        file: tasks/homebrew.yml

    - name: Zsh + Zim
      ansible.builtin.include_tasks:
        file: tasks/zsh-zim.yml

    - name: Git
      ansible.builtin.include_tasks:
        file: tasks/git.yml

    - name: macOS Defaults
      ansible.builtin.include_tasks:
        file: tasks/macos-defaults.yml

    - name: App Preferences
      ansible.builtin.include_tasks:
        file: tasks/app-preferences.yml

    - name: Cursor Editor
      ansible.builtin.include_tasks:
        file: tasks/cursor.yml
