- name: x86
  gather_facts: true
  hosts: primary_lxc
  tasks:
    - name: Initial setup
      ansible.builtin.include_tasks:
        file: tasks/initial-setup.yml

    - name: zsh
      ansible.builtin.include_tasks:
        file: tasks/zsh.yml

    - name: Setup nvim
      ansible.builtin.include_tasks:
        file: tasks/vim.yml

    - name: Install Docker
      ansible.builtin.include_tasks:
        file: tasks/docker.yml

    - name: SSH
      ansible.builtin.include_tasks:
        file: tasks/ssh.yml

    - name: Hardware Transcoding
      ansible.builtin.include_tasks:
        file: tasks/hw-transcode.yml

    - name: Unattended upgrades
      ansible.builtin.include_tasks:
        file: tasks/unattended-upgrades.yml

    - name: Docker prune
      ansible.builtin.include_tasks:
        file: tasks/docker-prune.yml