version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    container_name: gluetun
    networks:
      - internal-net
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8080:8080     # qBittorrent
      - 8888:8888/tcp # HTTP proxy
    volumes:
      - "${DOCKER_VOLUME_PATH}"/gluetun:/gluetun
    environment:
      - HTTPPROXY=on
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      # Wireguard:
      - SERVER_HOSTNAMES=uk-lon.prod.surfshark.com
      - WIREGUARD_PRIVATE_KEY=uDymMz0D2jX5ZPTXNHoCRJVcDsXZgMXaNiEGXJ7Eknk=
      - WIREGUARD_ADDRESSES=10.14.0.2/16
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gluetun.rule=Host(`torrent.pi.local`)"
      - "traefik.http.routers.gluetun.entrypoints=web"
      - "traefik.http.services.gluetun.loadbalancer.server.port=8080"

networks:
  internal-net:
    external: true
