version: '3.3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    container_name: portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - "$DOCKER_VOLUME_PATH/portainer:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.pi.local`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - internal-net

networks:
  internal-net:
    external: true
