services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    networks:
      - internal-net
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - "$DOCKER_VOLUME_PATH/readarr:/config"
      - "$MEDIA_MOUNT_PATH/books:/books"
      - "$DOWNLOADS_MOUNT_PATH:/downloads"
    ports:
      - 8787:8787
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  internal-net:
    external: true
