version: '3.3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /mnt/ssd/docker/home-server/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  portainer_data:

