services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:arm64v8-libtorrentv1 # https://github.com/qdm12/gluetun/discussions/1562#discussioncomment-5889922
    restart: unless-stopped
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8081
    volumes:
      - "$DOCKER_VOLUME_PATH/qbittorrent:/config"
      - "$DOWNLOADS_MOUNT_PATH:/downloads"
      - "$MEDIA_MOUNT_PATH/movies:/movies"
      - "$MEDIA_MOUNT_PATH/tv-shows:/tv-shows"
    network_mode: container:gluetun # run on the vpn network
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
