services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN_PRIMARY}
      - TUNNEL_METRICS=0.0.0.0:60123
    networks:
      - internal-net
    healthcheck:
      test: [ "CMD", "cloudflared", "tunnel", "--metrics", "localhost:60123", "ready" ]
      interval: 30s
      timeout: 30s
      retries: 3


networks:
  internal-net:
    external: true
