services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=eyJhIjoiNTY3Y2Q1ZmVkYjExZDZlOTJhZmI0NTRlNmUwMjA2ZTgiLCJ0IjoiYjQ2MTYwOTgtNmE5OS00MzZjLTk1NjEtODI3Y2RjZTM4NDlkIiwicyI6Ik1ESTRaR05rTXpZdFpUYzNZaTAwWldNeUxXRTJaVEl0T1dFMk9ERmpZamRrTVdNNSJ9
      - TUNNEL_METRICS=0.0.0.0:60123
    networks:
      - internal-net
    healthcheck:
      test: [ "CMD", "cloudflared", "tunnel", "--metrics", "localhost:60123", "ready" ]
      interval: 30s
      timeout: 30s
      retries: 3


networks:
  internal-net:
    external: true
